title: Vikram Kamath
affiliation: Saarland University
email: vica001 (at) teams.uni-saarland.de
google_scholar: https://scholar.google.com/citations?user=HVuuUzwAAAAJ&hl=en
github_link: https://twitter.com/kmarkiv
linkedin: https://www.linkedin.com/in/vikramkamathc/
avatar: ./assets/avatar.jpg
favicon: ./assets/img/favicon.png
cv: ./static/Vikram_Kamath_CV.pdf
favicon_dark: ./assets/img/favicon-dark.png
description: simple guy. researcher, programmer, and swimmer.Â 
canonical: https://kmarkiv.com
calendar: https://calendly.com/kmarkiv/vikram
position: Postdoctoral Fellow
google_analytics: UA-12079075-1
remote_theme: yaoyao-liu/minimal-light
cv_link: https://bit.ly/vikram_cv_web 
thesis_link: https://kilthub.cmu.edu/articles/thesis/DIA_Supporting_Teacher_Professional_Development_in_Low_Infrastructure_Settings/25135118?file=44377391

#theme: jekyll-theme-minimal
#https://kmarkiv.com/assets/Vikram_Kamath_CV-4.pdf
